### ISSUE TITLE
no- вместо is-not-

### ISSUE THREAD

**Issue by babenkoma** [WezomAgency/browserizr#11]
Хорошо бы css-классы сделать по аналогии с modernizr: mobile и no-mobile. Класс is-not-mobile слишком длинный. И не то, что бы долго писать, просто как по мне такая длина не оправдана. И если использовать вместе с modernizr, то классы browserizr будут по структуре отличаться от классов modernizr, что по моему мнению не красиво)

**Comment by babenkoma** [comment]
Еще как вариант можно сделать опцию, которая бы могла менять эти приставки

**Comment by dutchenkoOleg** [comment]
@babenkoma добавил геттеры/сеттеры для кастомных префиксов.
теперь можно указывать собственные, описание тут - https://github.com/WezomAgency/browserizr#change-prefixes
