### ISSUE TITLE
Кастомные тесты

### ISSUE THREAD

**Issue by babenkoma** [WezomAgency/browserizr#12]
Можно было бы добавить возможность добавить кастомные тесты. Это может быть полезно, когда установлен browserizr и не хочется устанавливать еще и modernizr, а проще добавить оттуда пару дополнительных тестов

**Comment by OlehDutchenko** [comment]
@babenkoma Этот пакет мы архивируем и больше не поддерживаем.
Используй [@wezom/browserizr](https://github.com/WezomCompany/browserizr#readme).
